#Porta del server 
server.port=8080

#Nome dell'applicazione 
spring.application.name=bootcamp-api

#Livello di log (INFO, DEBUG, WARN, ERROR)
logging.level.root=INFO
logging.level.it.corso.bootcamp=DEBUG

#Messaggio personalizzato (lettura con @Value)
app.messaggio=Benvenuto nel Bootcamp Spring Boot